### ISSUE TITLE
Standardise log file names

### ISSUE THREAD

**Issue by roysubs** [sirrus233/wotr-ladder-update#9]
Every player names their log files differently, often with spoiler info about who won the game (so that if you have that file, you already know who won before you watch, spoiling a large part of tension to replaying a game), or with their own real names instead of their Discord / Ladder names. Also, various logs appear without the ".log" extension (I think this is a MacOS thing, but the Windows client expects to see ".log" in the name when loading files).

It could simplify things to have a generic naming convention for all log files if the `wotr-ladder-update` script could rename the uploaded files when updating the ladder:
```
[date_time]_FPplayername_vs_SPplayername.log
```
All of this information is available from the WOTR Game Report form, and would make it easy to sort all games by date, or to find games involving specific users etc, making for a more consistent (and spoiler-free) archive of game logs.

**Comment by sirrus233** [comment]
Had to revert this feature, because it can't currently be done safely. Need to figure out a better way to manage permissions so that people's personal Drives are not exposed.

**Comment by sirrus233** [comment]
#13 takes another crack at this. Waiting for testing before the merge.
